# Generated by Django 5.0.4 on 2024-05-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0002_blog_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
