# Generated by Django 5.0.4 on 2024-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0004_alter_contact_name_alter_enquiry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
