# Generated by Django 5.0.4 on 2024-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0005_alter_subscription_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
