# Generated by Django 5.0.4 on 2024-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0007_delete_post_gallery_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='posted_date',
            field=models.CharField(max_length=20),
        ),
    ]
