# Generated by Django 5.0.4 on 2024-06-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0008_alter_gallery_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='posted_date',
        ),
    ]
