# Generated by Django 5.0.4 on 2024-06-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0010_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='blog',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='industry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testimo',
            name='job',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testimo',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testimo',
            name='testimonial',
            field=models.TextField(max_length=300),
        ),
    ]
