# Generated by Django 5.0.4 on 2024-06-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0011_delete_mymodel_alter_blog_caption_alter_blog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
