# Generated by Django 5.0.4 on 2024-06-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0013_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
