# Generated by Django 5.0.4 on 2024-06-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tezcoapp', '0014_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
